#include <stdint.h>

struct dns_header2 {
    /* dentifier: A 16-bit identification field generated by the device that creates the DNS query. 
    It is copied by the server into the response, so it can be used by that device 
    to match that query to the corresponding reply received from a DNS server */
    uint16_t ID;
    union generic_flags {
        struct bit_flags {
            uint16_t QR : 1;       // Query/Response 0 on query
            uint16_t opcode : 4;   // detailed shit about query
            uint16_t AA : 1;       // indicate if generated by authority
            uint16_t TC : 1;       // indicate if message is truncated
            uint16_t RD : 1;
            /* Recursion Available: 
             * Set to 1 or cleared to 0 in a response to indicate whether the 
             * server creating the response supports recursive queries 
             */
            uint16_t RA : 1;
            uint16_t Z : 3;        // shoud be zero
            uint16_t Rcode : 4;    // response code
        } bit_flags;
        uint16_t bits;
    } generic_flags;

    /* Question Count: 
    * Specifies the number of questions in the Question section of the message. 
    */
    uint16_t QDcount;
    /* Answer Record Count:
     * Specifies the number of resource records in the Answer section of the message. 
     */
    uint16_t ANcount;
    /* Authority Record Count: 
     * Specifies the number of resource records in the Authority section of the message. 
     * (“NS” stands for “name server”, of course. J) 
     */
    uint16_t NScount;
    /* Additional Record Count: 
     * Specifies the number of resource records in the Additional section of the message. 
     */
    uint16_t ARcount;
};

/* gets pointer and buffer where to store domain. Returns how many bytes it was listened */
int get_domain(char *p, char *buf, int maxs);

/* 
 *  compairs two domains in register independent way + ignoring trailing dot 
 *  gOOgle.COM  =   google.com.
 *  googl.com  != google.com.
 *  0 - equal; 1 - false
 */ 
int compair_domains(char *d1, char *d2);